### gossip info
GET http://localhost:7951/actuator/gossip

### leave from gossip cluster
POST http://localhost:7951/actuator/gossip/shutdown

### post gossip event
POST http://localhost:7951/actuator/gossip/event
Content-Type: application/vnd.spring-boot.actuator.v2+json

{
  "type": "com.foobar.user.LoginEvent",
  "source": "source-1",
  "datacontenttype": "text/plain",
  "data": "uid:1234"
}


###
